services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=users
      - POSTGRES_PASSWORD=123
  web:
    build: .
    command: uwsgi --http 0.0.0.0:8000 --module distributed.wsgi
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=users
      - DB_USER=users
      - DB_PASS=123
      - DB_HOST=db
    depends_on:
      - db
#  nginx:
#    container_name: nginx_container
#    build: ./nginx
#    ports:
#      - 80:80
